//try-and-catch
let products;

try{
    products.forEach(item => console.log(item))
} catch(error){
    console.log("error: ", error)
}